apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2020-01-21T23:37:55Z"
  name: ns-admin
  namespace: section3
  resourceVersion: "149805"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/section3/rolebindings/ns-admin
  uid: 5bd636c3-1b71-473d-b971-522c0bf21800
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: myuser
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: AppGroup1
