apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-s3-admin
  namespace: section3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-s3
subjects:
- kind: ServiceAccount
  name: s3-admin
  namespace: section3
