apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2020-01-22T00:27:20Z"
  name: s3-viewer
  namespace: section3
  resourceVersion: "153289"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/section3/rolebindings/s3-viewer
  uid: f9849955-198d-46bc-b5bc-2af4c14814d8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-s3
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: myuser
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: JobOperator
