{
 "title": "Command Center",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Front End Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"front-end.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Catalogue Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"catalogue.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Carts Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"carts.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Orders Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"orders.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Payment Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"payment.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Session Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"session-db.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Shipping Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"shipping.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Users Errors",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "avg by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"user.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Client Failure Rate (5xx responses)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"front-end.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "FrontEnd {{response_code}}"
    },
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"orders.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Orders {{response_code}}"
    },
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"user.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "User {{response_code}}"
    },
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"catalogue.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Catalog {{response_code}}"
    },
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"carts.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Carts {{response_code}}"
    },
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"payment.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Payments {{response_code}}"
    },
    {
     "expr": "avg by(response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"shipping.sock-shop.svc.cluster.local\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Shipping {{response_code}}"
    }
   ]
  },
  {
   "title": "Service RPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"front-end.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "FrontEnd"
    },
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"orders.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "Orders"
    },
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"user.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "User"
    },
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"catalogue.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "Catalog"
    },
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"carts.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "Carts"
    },
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"payment.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "Payment"
    },
    {
     "expr": "sum by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"shipping.sock-shop.svc.cluster.local\",response_code=\"200\"}[5m]))",
     "legendFormat": "Shipping"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_pod_count{instance=\"aks-agentpool-33086131-vmss000000\"}",
     "legendFormat": "Node1"
    },
    {
     "expr": "kubelet_running_pod_count{instance=\"aks-agentpool-33086131-vmss000001\"}",
     "legendFormat": "Node2"
    },
    {
     "expr": "kubelet_running_pod_count{instance=\"aks-agentpool-33086131-vmss000002\"}",
     "legendFormat": "Node3"
    }
   ]
  },
  {
   "title": "Unauthorized Logins",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(destination_service)(rate(istio_requests_total{reporter=\"source\",destination_service=\"front-end.sock-shop.svc.cluster.local\",response_code=\"401\"}[5m]))",
     "legendFormat": "Unauthorized"
    }
   ]
  },
  {
   "title": "DB Service Failure Rate (5xx responses)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(destination_service,response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"orders-db\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Orders {{response_code}}"
    },
    {
     "expr": "avg by(destination_service,response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"users-db\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "User {{response_code}}"
    },
    {
     "expr": "avg by(destination_service,response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"catalogue-db\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Catalog {{response_code}}"
    },
    {
     "expr": "avg by(destination_service,response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"carts-db\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Carts {{response_code}}"
    },
    {
     "expr": "avg by(destination_service,response_code)(rate(istio_requests_total{reporter=\"source\",destination_service=\"session-db\",response_code!~\"2..\"}[5m]))",
     "legendFormat": "Session {{response_code}}"
    }
   ]
  }
 ]
}